CREATE CACHED TABLE "PUBLIC"."COMPANY"(
    "ID" UUID NOT NULL,
    "NAME" CHARACTER VARYING(256)
);
ALTER TABLE "PUBLIC"."COMPANY" ADD CONSTRAINT "PUBLIC"."PK_COMPANY" PRIMARY KEY("ID");
CREATE CACHED TABLE "PUBLIC"."CREATED_BY_KOMAPPER"(
    "ID" UUID NOT NULL,
    "NAME" CHARACTER VARYING(256)
);
CREATE CACHED TABLE "PUBLIC"."EMPLOYEE"(
    "ID" UUID NOT NULL,
    "COMPANY_ID" UUID NOT NULL,
    "NEW_NAME" CHARACTER VARYING(256),
    "NOT_NULL_NAME" CHARACTER VARYING(256) NOT NULL
);
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT "PUBLIC"."PK_EMPLOYEE" PRIMARY KEY("ID");
CREATE INDEX "PUBLIC"."EMPLOYEE_COMPANY_ID_FKEY_INDEX_21" ON "PUBLIC"."EMPLOYEE"("COMPANY_ID" NULLS FIRST);
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT "PUBLIC"."EMPLOYEE_COMPANY_ID_FKEY" FOREIGN KEY("COMPANY_ID") REFERENCES "PUBLIC"."COMPANY"("ID") ON DELETE CASCADE NOCHECK;