name: test master-version Liquibase

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'

env:
  JDK_DISTRIBUTION: 'temurin'
  JDK_VERSION: '21'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4

      # see https://github.com/liquibase/liquibase/actions/workflows/build-main.yml
      - name: Fetch latest master-version from GitHub Packages
        id: liquibase-core-master-version
        uses: momosetkn/fetch-gh-package-latest-snapshot-version@main
        with:
          org: liquibase
          packageType: maven
          packageName: org.liquibase.liquibase-core
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          versionPattern: '^.{7}-SNAPSHOT$' # for master-branch condition

      - name: Configure Gradle for GitHub Packages
        run: |
          echo "gpr.user=${{ github.actor }}" >> gradle.properties
          echo "gpr.token=${{ secrets.GITHUB_TOKEN }}" >> gradle.properties

      - name: Test with latest liquibase master-version
        run: |
          ./gradlew test -PliquibaseVersion=${{ steps.liquibase-core-master-version.outputs.version }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'reports-${{ matrix.os }}'
          path: ./**/build/reports
