name: test master-version Liquibase

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'

permissions:
  # Required: when using dependency-graph: generate-and-submit,
  # the GITHUB_TOKEN must have contents: write permission
  contents: write

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v5

      - name: Setup Gradle with GitHub Packages
        uses: ./.github/actions/setup-gradle-with-gpr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}

      # see https://github.com/liquibase/liquibase/actions/workflows/build-main.yml
      - name: Fetch latest master-version from GitHub Packages
        id: liquibase-core-master-version
        uses: momosetkn/fetch-gh-package-latest-snapshot-version@main
        with:
          org: liquibase
          packageType: maven
          packageName: org.liquibase.liquibase-core
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          versionPattern: '^.{7}-SNAPSHOT$' # for master-branch condition

      - name: Test with latest liquibase master-version
        run: |
          ./gradlew test -PliquibaseVersion=${{ steps.liquibase-core-master-version.outputs.version }}

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'reports-${{ matrix.os }}'
          path: ./**/build/reports
